name: build & deploy
on:
  push:
  pull_request:
jobs:
  java-build:
    name: Build java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: corretto
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.2
      - name: Gradle build
        run: gradle graphql-doc-directive:build graphql-doc-directive-gradle-plugin:build
      - uses: actions/upload-artifact@v3
        with:
          name: directive artifacts
          path: graphql-doc-directive/build
      - uses: actions/upload-artifact@v3
        with:
          name: plugin artifacts
          path: graphql-doc-directive-gradle-plugin/build
  deploy-java:
    name: Publish directive
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: java interface artifacts
      - uses: actions/download-artifact@v3
        with:
          name: directive artifacts
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: corretto
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.2
      - name: Publish libraries
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: gradle graphql-doc-directive:publish --no-daemon
  deploy-plugin:
    name: Publish plugin
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: plugin artifacts
          path: graphql-doc-directive-gradle-plugin/build
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: corretto
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.2
      - id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: graphql-doc-directive-gradle-plugㅡin/**
      - name: Publish plugin
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        run: gradle graphql-doc-directive-gradle-plugin:publishPlugins
